import { Target } from "./target";

export const TARGETS: Target[] = [
  {
    id: 0,
    acquisitionStatus: "researching",
    industry: "Electronics",
    companyName: "Champ Lexington",
    companyAddress: "7663 Parklake Street",
    companySize: 863,
    ceo: "Margaret Chinchharni",
    cfo: "Sheverly Williamsons",
    cto: "Tanner Brightside",
    liquidity: 99,
    profitability: 82,
    growth: 96,
    valuation: 94.61
  },
  {
    id: 1,
    acquisitionStatus: "researching",
    industry: "Capital Goods",
    companyName: "Emmerich, Hand and Wisozk",
    companyAddress: "0112 Rutledge Crossing",
    companySize: 180,
    ceo: "Thebault Fredson",
    cfo: "Joscelin Dreschler",
    cto: "Benoit Crudgington",
    liquidity: 49,
    profitability: 90,
    growth: 24,
    valuation: 3.27
  },
  {
    id: 2,
    acquisitionStatus: "approved",
    industry: "Manufacturing",
    companyName: "Johns-Hamill",
    companyAddress: "9 Macpherson Alley",
    companySize: 16391,
    ceo: "Seth Whannel",
    cfo: "Marjy Eadmead",
    cto: "Hatty Hampe",
    liquidity: 60,
    profitability: 11,
    growth: 55,
    valuation: 93.02
  },
  {
    id: 3,
    acquisitionStatus: "researching",
    industry: "Finance",
    companyName: "Dicki, Ortiz and Hahn",
    companyAddress: "9343 Hanson Junction",
    companySize: 19916,
    ceo: "Tressa Easseby",
    cfo: "Deva Thebes",
    cto: "Karolina Lemarie",
    liquidity: 98,
    profitability: 62,
    growth: 50,
    valuation: 4.11
  },
  {
    id: 4,
    acquisitionStatus: "pending approval",
    industry: "Manufacturing",
    companyName: "Moore, Konopelski and Kovacek",
    companyAddress: "2 Nova Way",
    companySize: 15658,
    ceo: "Jaime Penberthy",
    cfo: "Lira Birckmann",
    cto: "Jacky Durman",
    liquidity: 56,
    profitability: 4,
    growth: 32,
    valuation: 434.22
  },
  {
    id: 5,
    acquisitionStatus: "researching",
    industry: "Health Care",
    companyName: "Goyette-Stehr",
    companyAddress: "372 Lake View Way",
    companySize: 17312,
    ceo: "Nadeen Wisbey",
    cfo: "Duane Ferraretto",
    cto: "Pegeen Mapplethorpe",
    liquidity: 19,
    profitability: 44,
    growth: 17,
    valuation: 11.27
  },
  {
    id: 6,
    acquisitionStatus: "researching",
    industry: "Health Care",
    companyName: "Jacobi-Effertz",
    companyAddress: "5826 Fordem Drive",
    companySize: 5678,
    ceo: "Ernest Logg",
    cfo: "Sigismond Normaville",
    cto: "Ryon Tolomio",
    liquidity: 36,
    profitability: 87,
    growth: 97,
    valuation: 103.1
  },
  {
    id: 7,
    acquisitionStatus: "researching",
    industry: "Capital Goods",
    companyName: "Halvorson LLC",
    companyAddress: "09480 Sunbrook Way",
    companySize: 17651,
    ceo: "Rebe Kellington",
    cfo: "Nari Feragh",
    cto: "Stefa Simecek",
    liquidity: 85,
    profitability: 13,
    growth: 87,
    valuation: 9.66
  },
  {
    id: 8,
    acquisitionStatus: "approved",
    industry: "Consumer Services",
    companyName: "Boyle, Rau and Hudson",
    companyAddress: "880 Meadow Ridge Center",
    companySize: 17717,
    ceo: "Rob Andre",
    cfo: "Conroy Hendriks",
    cto: "Dicky Clemmey",
    liquidity: 96,
    profitability: 3,
    growth: 30,
    valuation: 16.58
  },
  {
    id: 9,
    acquisitionStatus: "pending approval",
    industry: "Finance",
    companyName: "Lubowitz and Sons",
    companyAddress: "553 Fremont Road",
    companySize: 12482,
    ceo: "Cristina Thowless",
    cfo: "Koral Stoddard",
    cto: "Elena Fist",
    liquidity: 86,
    profitability: 41,
    growth: 72,
    valuation: 6.19
  },
  {
    id: 10,
    acquisitionStatus: "declined",
    industry: "Public Utilities",
    companyName: "Powlowski, Boehm and Veum",
    companyAddress: "51 John Wall Plaza",
    companySize: 1731,
    ceo: "Fernando Doogan",
    cfo: "Brew Haysar",
    cto: "Laird Janew",
    liquidity: 34,
    profitability: 38,
    growth: 17,
    valuation: 1.64
  },
  {
    id: 11,
    acquisitionStatus: "pending approval",
    industry: "Finance",
    companyName: "Kunde, Brown and Rowe",
    companyAddress: "688 American Ash Plaza",
    companySize: 11929,
    ceo: "Wilmar Tyer",
    cfo: "Florian Abrahams",
    cto: "Terrill Fley",
    liquidity: 66,
    profitability: 65,
    growth: 48,
    valuation: 666.52
  },
  {
    id: 12,
    acquisitionStatus: "pending approval",
    industry: "Health Care",
    companyName: "Dietrich, Ledner and Grant",
    companyAddress: "2 Magdeline Pass",
    companySize: 1349,
    ceo: "Dorris Culver",
    cfo: "Wade Fillan",
    cto: "Clemens Ruddock",
    liquidity: 83,
    profitability: 58,
    growth: 89,
    valuation: 38.16
  },
  {
    id: 13,
    acquisitionStatus: "approved",
    industry: "Manufacturing",
    companyName: "Heller Inc",
    companyAddress: "54512 Browning Drive",
    companySize: 733,
    ceo: "Ashbey Yesenin",
    cfo: "Noble Stobbs",
    cto: "Gipsy Smoughton",
    liquidity: 57,
    profitability: 44,
    growth: 84,
    valuation: 61.57
  },
  {
    id: 14,
    acquisitionStatus: "declined",
    industry: "Public Utilities",
    companyName: "Brown LLC",
    companyAddress: "43187 Oakridge Alley",
    companySize: 12020,
    ceo: "Ashil Renak",
    cfo: "Ansel Fredson",
    cto: "Lionello Van den Bosch",
    liquidity: 56,
    profitability: 61,
    growth: 99,
    valuation: 3.49
  },
  {
    id: 15,
    acquisitionStatus: "pending approval",
    industry: "Energy",
    companyName: "Schowalter, Bosco and Fahey",
    companyAddress: "1808 Onsgard Street",
    companySize: 8386,
    ceo: "Lizzie Eilers",
    cfo: "Amber Bulbeck",
    cto: "Emmalynne Wrankling",
    liquidity: 28,
    profitability: 96,
    growth: 92,
    valuation: 39.11
  },
  {
    id: 16,
    acquisitionStatus: "declined",
    industry: "Consumer Services",
    companyName: "Cruickshank-Koepp",
    companyAddress: "47576 Darwin Court",
    companySize: 12355,
    ceo: "Ema O'Sheerin",
    cfo: "Lief Tyson",
    cto: "Cordey McGonagle",
    liquidity: 25,
    profitability: 69,
    growth: 91,
    valuation: 1.78
  },
  {
    id: 17,
    acquisitionStatus: "approved",
    industry: "Consumer Durables",
    companyName: "Koch-Schroeder",
    companyAddress: "3249 Iowa Crossing",
    companySize: 9127,
    ceo: "Kory Bellson",
    cfo: "Cass Nerney",
    cto: "Ezra Radband",
    liquidity: 3,
    profitability: 1,
    growth: 3,
    valuation: 1.51
  },
  {
    id: 18,
    acquisitionStatus: "declined",
    industry: "Basic Industries",
    companyName: "Nicolas LLC",
    companyAddress: "206 Waywood Park",
    companySize: 6338,
    ceo: "Rosa Grimshaw",
    cfo: "Danila Pether",
    cto: "Marabel Hobell",
    liquidity: 29,
    profitability: 56,
    growth: 66,
    valuation: 1.44
  },
  {
    id: 19,
    acquisitionStatus: "pending approval",
    industry: "Capital Goods",
    companyName: "Welch Inc",
    companyAddress: "1121 Village Trail",
    companySize: 15465,
    ceo: "Ulrika Peaseman",
    cfo: "Wenonah Grindell",
    cto: "Boniface Girodias",
    liquidity: 70,
    profitability: 87,
    growth: 79,
    valuation: 15.8
  },
  {
    id: 20,
    acquisitionStatus: "researching",
    industry: "Finance",
    companyName: "Jones Group",
    companyAddress: "42549 Grayhawk Crossing",
    companySize: 4715,
    ceo: "Rance Scain",
    cfo: "Perice Whybray",
    cto: "Jacqui Dallaghan",
    liquidity: 79,
    profitability: 100,
    growth: 7,
    valuation: 71.3
  },
  {
    id: 21,
    acquisitionStatus: "pending approval",
    industry: "Finance",
    companyName: "Adams-Walter",
    companyAddress: "36 John Wall Crossing",
    companySize: 14366,
    ceo: "Killy Readhead",
    cfo: "Erl Trase",
    cto: "Arney Bau",
    liquidity: 67,
    profitability: 69,
    growth: 37,
    valuation: 3.07
  },
  {
    id: 22,
    acquisitionStatus: "researching",
    industry: "Health Care",
    companyName: "Schinner, Lang and Kris",
    companyAddress: "7117 Main Drive",
    companySize: 11474,
    ceo: "Dee Guitel",
    cfo: "Gardener Benyon",
    cto: "Tammy Johns",
    liquidity: 76,
    profitability: 69,
    growth: 15,
    valuation: 1.54
  },
  {
    id: 23,
    acquisitionStatus: "researching",
    industry: "Consumer Services",
    companyName: "Ullrich-Rogahn",
    companyAddress: "66029 Ludington Court",
    companySize: 2748,
    ceo: "Ellsworth Nesterov",
    cfo: "Haily Newbatt",
    cto: "Mack Murrells",
    liquidity: 85,
    profitability: 100,
    growth: 3,
    valuation: 5.04
  },
  {
    id: 24,
    acquisitionStatus: "approved",
    industry: "Capital Goods",
    companyName: "Hamill, Dach and Hoeger",
    companyAddress: "296 Susan Alley",
    companySize: 17130,
    ceo: "Jean Chard",
    cfo: "Alick MacGebenay",
    cto: "Josi Kilbey",
    liquidity: 20,
    profitability: 66,
    growth: 52,
    valuation: 45.14
  },
  {
    id: 25,
    acquisitionStatus: "declined",
    industry: "Finance",
    companyName: "Hills-Balistreri",
    companyAddress: "1 Petterle Junction",
    companySize: 6586,
    ceo: "Phillida Kilbourne",
    cfo: "Emmit Secrett",
    cto: "Marthena Patkin",
    liquidity: 33,
    profitability: 75,
    growth: 46,
    valuation: 34.76
  },
  {
    id: 26,
    acquisitionStatus: "declined",
    industry: "Manufacturing",
    companyName: "Toy-Baumbach",
    companyAddress: "07291 Norway Maple Hill",
    companySize: 10932,
    ceo: "Zollie Garnsworth",
    cfo: "Janessa Panswick",
    cto: "Cirillo Skayman",
    liquidity: 64,
    profitability: 48,
    growth: 16,
    valuation: 3.87
  },
  {
    id: 27,
    acquisitionStatus: "pending approval",
    industry: "Transportation",
    companyName: "Bailey LLC",
    companyAddress: "98170 Rieder Park",
    companySize: 3111,
    ceo: "Aron Keam",
    cfo: "Min Grzegorecki",
    cto: "Rafaelita Bothwell",
    liquidity: 78,
    profitability: 23,
    growth: 48,
    valuation: 4.18
  },
  {
    id: 28,
    acquisitionStatus: "pending approval",
    industry: "Consumer Services",
    companyName: "Gutmann-Mertz",
    companyAddress: "488 Surrey Alley",
    companySize: 16193,
    ceo: "Leroy Marskell",
    cfo: "Dalis Kenion",
    cto: "Natty Stuttard",
    liquidity: 12,
    profitability: 71,
    growth: 49,
    valuation: 3.5
  },
  {
    id: 29,
    acquisitionStatus: "approved",
    industry: "Consumer Non-Durables",
    companyName: "Powlowski-Reichel",
    companyAddress: "171 Basil Alley",
    companySize: 12148,
    ceo: "Vivia Niland",
    cfo: "Trueman Yurtsev",
    cto: "Trude Barnes",
    liquidity: 31,
    profitability: 57,
    growth: 65,
    valuation: 7.24
  },
  {
    id: 30,
    acquisitionStatus: "researching",
    industry: "Finance",
    companyName: "O'Keefe-Heathcote",
    companyAddress: "5161 Kennedy Court",
    companySize: 6272,
    ceo: "Dionysus Aldcorne",
    cfo: "Othello Clutterham",
    cto: "Solly Croser",
    liquidity: 62,
    profitability: 24,
    growth: 92,
    valuation: 114.75
  },
  {
    id: 31,
    acquisitionStatus: "approved",
    industry: "Manufacturing",
    companyName: "Morar-Hahn",
    companyAddress: "72208 Transport Point",
    companySize: 16832,
    ceo: "Sonni Maddicks",
    cfo: "Teodoor Tapley",
    cto: "Jareb Thairs",
    liquidity: 33,
    profitability: 73,
    growth: 37,
    valuation: 180.01
  },
  {
    id: 32,
    acquisitionStatus: "declined",
    industry: "Health Care",
    companyName: "Ferry-Gleason",
    companyAddress: "95 Dixon Trail",
    companySize: 10313,
    ceo: "Massimiliano McDonell",
    cfo: "Lorne Brealey",
    cto: "Timoteo Maunton",
    liquidity: 34,
    profitability: 17,
    growth: 24,
    valuation: 23.56
  },
  {
    id: 33,
    acquisitionStatus: "researching",
    industry: "Technology",
    companyName: "Tillman and Sons",
    companyAddress: "60 Nova Lane",
    companySize: 4253,
    ceo: "Issy Gluyas",
    cfo: "Harwilll Naismith",
    cto: "Mariann Brandin",
    liquidity: 100,
    profitability: 13,
    growth: 37,
    valuation: 814.69
  },
  {
    id: 34,
    acquisitionStatus: "approved",
    industry: "Capital Goods",
    companyName: "Lang-Champlin",
    companyAddress: "4902 Springview Street",
    companySize: 19809,
    ceo: "Blanche Balharry",
    cfo: "Waverly Dorian",
    cto: "Tanner Hunton",
    liquidity: 97,
    profitability: 70,
    growth: 9,
    valuation: 4.61
  },
  {
    id: 35,
    acquisitionStatus: "approved",
    industry: "Technology",
    companyName: "Satterfield, Prosacco and Mayer",
    companyAddress: "605 Texas Parkway",
    companySize: 1453,
    ceo: "William Bonnet",
    cfo: "Fonz Russen",
    cto: "Happy Bilston",
    liquidity: 99,
    profitability: 91,
    growth: 9,
    valuation: 15.62
  },
  {
    id: 36,
    acquisitionStatus: "declined",
    industry: "Technology",
    companyName: "Rutherford-Tremblay",
    companyAddress: "574 Bartillon Junction",
    companySize: 18310,
    ceo: "Morgana Cremen",
    cfo: "Barri Shore",
    cto: "Lynnet Glentworth",
    liquidity: 65,
    profitability: 74,
    growth: 5,
    valuation: 2.67
  },
  {
    id: 37,
    acquisitionStatus: "declined",
    industry: "Manufacturing",
    companyName: "Beer, Reichert and Bechtelar",
    companyAddress: "103 Warner Lane",
    companySize: 3321,
    ceo: "Jarib Hebard",
    cfo: "Arvin Filipic",
    cto: "Pen Winspar",
    liquidity: 18,
    profitability: 66,
    growth: 35,
    valuation: 19.56
  },
  {
    id: 38,
    acquisitionStatus: "pending approval",
    industry: "Health Care",
    companyName: "Cormier Group",
    companyAddress: "88 Kingsford Way",
    companySize: 19331,
    ceo: "Angie Lipmann",
    cfo: "Rochelle Gummary",
    cto: "Yank Buckley",
    liquidity: 15,
    profitability: 88,
    growth: 37,
    valuation: 3.31
  },
  {
    id: 39,
    acquisitionStatus: "pending approval",
    industry: "Manufacturing",
    companyName: "Sauer, Pollich and Padberg",
    companyAddress: "37392 Banding Circle",
    companySize: 5055,
    ceo: "Ewan Rawson",
    cfo: "Frasier Lorain",
    cto: "Farleigh Keeting",
    liquidity: 81,
    profitability: 75,
    growth: 96,
    valuation: 30.4
  },
  {
    id: 40,
    acquisitionStatus: "declined",
    industry: "Manufacturing",
    companyName: "Strosin, Kassulke and Koepp",
    companyAddress: "3 Merry Trail",
    companySize: 16116,
    ceo: "Myrwyn Roofe",
    cfo: "Michele Pearde",
    cto: "Lorin Pickard",
    liquidity: 96,
    profitability: 56,
    growth: 44,
    valuation: 22.2
  },
  {
    id: 41,
    acquisitionStatus: "researching",
    industry: "Basic Industries",
    companyName: "Olson-Bednar",
    companyAddress: "7770 Farmco Center",
    companySize: 14712,
    ceo: "Ardelis Blanko",
    cfo: "Donny Connechy",
    cto: "Laurene Liverock",
    liquidity: 69,
    profitability: 17,
    growth: 51,
    valuation: 63.24
  },
  {
    id: 42,
    acquisitionStatus: "researching",
    industry: "Energy",
    companyName: "Kuphal, Goldner and Kuhic",
    companyAddress: "18894 Mitchell Alley",
    companySize: 18448,
    ceo: "Freddie Mustill",
    cfo: "Waverley Ryburn",
    cto: "Katharina Kristof",
    liquidity: 27,
    profitability: 63,
    growth: 1,
    valuation: 664.71
  },
  {
    id: 43,
    acquisitionStatus: "approved",
    industry: "Capital Goods",
    companyName: "Roberts, McCullough and D'Amore",
    companyAddress: "37 Ramsey Avenue",
    companySize: 3450,
    ceo: "Sybila Durn",
    cfo: "Case Eneas",
    cto: "Lillian Service",
    liquidity: 65,
    profitability: 85,
    growth: 85,
    valuation: 610.36
  },
  {
    id: 44,
    acquisitionStatus: "pending approval",
    industry: "Finance",
    companyName: "Ankunding-Frami",
    companyAddress: "7 Pearson Court",
    companySize: 19830,
    ceo: "Dewey Benion",
    cfo: "Isidoro Sangwin",
    cto: "Binny Kelloway",
    liquidity: 35,
    profitability: 87,
    growth: 81,
    valuation: 14.4
  }
];
